# Generated by Django 4.2.7 on 2026-02-16 05:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(choices=[('scope_1', 'Scope 1 - Emisiones Directas'), ('scope_2', 'Scope 2 - Emisiones Indirectas de Energía'), ('scope_3', 'Scope 3 - Otras Emisiones Indirectas')], max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alcance de Emisiones',
                'verbose_name_plural': 'Alcances de Emisiones',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Factor')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('data_type', models.CharField(choices=[('numeric', 'Numérico'), ('percentage', 'Porcentaje'), ('text', 'Texto'), ('boolean', 'Sí/No'), ('date', 'Fecha')], default='numeric', max_length=20, verbose_name='Tipo de Dato')),
                ('unit', models.CharField(blank=True, choices=[('ton', 'Toneladas'), ('kg', 'Kilogramos'), ('kwh', 'Kilovatios-hora'), ('m3', 'Metros cúbicos'), ('l', 'Litros'), ('percentage', 'Porcentaje'), ('count', 'Cantidad'), ('hours', 'Horas'), ('days', 'Días'), ('currency', 'Moneda'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Unidad de Actividad')),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Factor de Emisión')),
                ('emission_unit', models.CharField(blank=True, help_text='Ej: kgCO2e', max_length=50, null=True, verbose_name='Unidad de Emisión')),
                ('gri_standard', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estándar GRI')),
                ('sasb_standard', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estándar SASB')),
                ('tcfd_standard', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estándar TCFD')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='api.organization')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factors', to='carbon.emissionscope', verbose_name='Alcance/Scope')),
            ],
            options={
                'verbose_name': 'Factor de Emisión',
                'verbose_name_plural': 'Factores de Emisión',
                'ordering': ['scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarbonPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Período')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_carbon_periods', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carbon_periods', to='api.organization')),
            ],
            options={
                'verbose_name': 'Período de Carbono',
                'verbose_name_plural': 'Períodos de Carbono',
                'ordering': ['-start_date'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='CarbonDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(verbose_name='Fecha')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Cantidad')),
                ('uncertainty_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Incertidumbre (%)')),
                ('calculated_emission', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Emisión Calculada (kgCO₂e)')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor Numérico')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Valor Texto')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Valor Booleano')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Valor Fecha')),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor Meta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completado'), ('reviewed', 'Revisado'), ('approved', 'Aprobado')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='carbon/evidence/', verbose_name='Archivo de Evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_carbon_data', to=settings.AUTH_USER_MODEL)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='carbon.emissionfactor', verbose_name='Factor de Emisión')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carbon_data_entries', to='api.organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='carbon.carbonperiod', verbose_name='Período')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_carbon_data', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Registro de Emisiones',
                'verbose_name_plural': 'Registros de Emisiones',
                'ordering': ['-collection_date', 'factor'],
                'unique_together': {('period', 'factor', 'collection_date')},
            },
        ),
    ]
