# Generated by Django 4.2.7 on 2026-01-06 02:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(choices=[('environmental', 'Ambiental'), ('social', 'Social'), ('governance', 'Gobernanza')], max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría ESG',
                'verbose_name_plural': 'Categorías ESG',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ESGComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estándar')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versión')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estándar de Cumplimiento',
                'verbose_name_plural': 'Estándares de Cumplimiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ESGScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(choices=[('scope_1', 'Scope 1 - Emisiones Directas'), ('scope_2', 'Scope 2 - Emisiones Indirectas de Energía'), ('scope_3', 'Scope 3 - Otras Emisiones Indirectas')], max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='esg.esgcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Origen/Scope ESG',
                'verbose_name_plural': 'Orígenes/Scopes ESG',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ESGPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Período')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_esg_periods', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esg_periods', to='api.organization')),
            ],
            options={
                'verbose_name': 'Período ESG',
                'verbose_name_plural': 'Períodos ESG',
                'ordering': ['-start_date'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='ESGMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Métrica')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('data_type', models.CharField(choices=[('numeric', 'Numérico'), ('percentage', 'Porcentaje'), ('text', 'Texto'), ('boolean', 'Sí/No'), ('date', 'Fecha')], default='numeric', max_length=20, verbose_name='Tipo de Dato')),
                ('unit', models.CharField(blank=True, choices=[('ton', 'Toneladas'), ('kg', 'Kilogramos'), ('kwh', 'Kilovatios-hora'), ('m3', 'Metros cúbicos'), ('l', 'Litros'), ('percentage', 'Porcentaje'), ('count', 'Cantidad'), ('hours', 'Horas'), ('days', 'Días'), ('currency', 'Moneda'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Unidad')),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Factor de Emisión')),
                ('emission_unit', models.CharField(blank=True, help_text='Ej: kgCO2e', max_length=50, null=True, verbose_name='Unidad de Emisión')),
                ('gri_standard', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estándar GRI')),
                ('sasb_standard', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estándar SASB')),
                ('tcfd_standard', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estándar TCFD')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='esg.esgcategory', verbose_name='Categoría')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esg_metrics', to='api.organization')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='esg.esgscope', verbose_name='Origen/Scope')),
            ],
            options={
                'verbose_name': 'Métrica ESG',
                'verbose_name_plural': 'Métricas ESG',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ESGGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Objetivo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor Meta')),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Actual')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('target_date', models.DateField(verbose_name='Fecha Meta')),
                ('status', models.CharField(choices=[('on_track', 'En Camino'), ('at_risk', 'En Riesgo'), ('delayed', 'Retrasado'), ('achieved', 'Alcanzado'), ('cancelled', 'Cancelado')], default='on_track', max_length=20, verbose_name='Estado')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='esg.esgcategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_esg_goals', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='esg.esgmetric', verbose_name='Métrica Asociada')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esg_goals', to='api.organization')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_esg_goals', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Objetivo ESG',
                'verbose_name_plural': 'Objetivos ESG',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ESGAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('expected_impact', models.TextField(blank=True, null=True, verbose_name='Enfoque/Impacto Esperado')),
                ('actual_result', models.TextField(blank=True, null=True, verbose_name='Resultado Real/Logro')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('in_progress', 'En Progreso'), ('paused', 'Pausado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='planned', max_length=20, verbose_name='Estado')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso %')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Presupuesto')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costo Real')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='esg.esgcategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_esg_actions', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='esg.esggoal', verbose_name='Objetivo Asociado')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='esg.esgmetric', verbose_name='Métrica Asociada')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esg_actions', to='api.organization')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_esg_actions', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('team_members', models.ManyToManyField(blank=True, related_name='esg_action_team', to=settings.AUTH_USER_MODEL, verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Acción ESG',
                'verbose_name_plural': 'Acciones ESG',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ESGDataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(verbose_name='Fecha')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Cantidad')),
                ('uncertainty_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Incertidumbre (%)')),
                ('calculated_emission', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Emisión Calculada')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor Numérico')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Valor Texto')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Valor Booleano')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Valor Fecha')),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor Meta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completado'), ('reviewed', 'Revisado'), ('approved', 'Aprobado')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='esg/evidence/', verbose_name='Archivo de Evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_esg_data', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_collections', to='esg.esgmetric', verbose_name='Factor de Emisión/Métrica')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esg_data_collections', to='api.organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_collections', to='esg.esgperiod', verbose_name='Período')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_esg_data', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Colección de Datos ESG',
                'verbose_name_plural': 'Colecciones de Datos ESG',
                'ordering': ['-collection_date', 'metric'],
                'unique_together': {('period', 'metric', 'collection_date')},
            },
        ),
    ]
