# Generated by Django 4.2.7 on 2026-02-16 05:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(choices=[('environmental', 'Ambiental'), ('social', 'Social'), ('governance', 'Gobernanza')], max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría ESG',
                'verbose_name_plural': 'Categorías ESG',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ESGComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estándar')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versión')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estándar de Cumplimiento',
                'verbose_name_plural': 'Estándares de Cumplimiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ESGGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Objetivo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor Meta')),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Actual')),
                ('unit', models.CharField(blank=True, help_text='Ej: tonCO₂e, %, kWh', max_length=50, null=True, verbose_name='Unidad')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('target_date', models.DateField(verbose_name='Fecha Meta')),
                ('status', models.CharField(choices=[('on_track', 'En Camino'), ('at_risk', 'En Riesgo'), ('delayed', 'Retrasado'), ('achieved', 'Alcanzado'), ('cancelled', 'Cancelado')], default='on_track', max_length=20, verbose_name='Estado')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='esg.esgcategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_esg_goals', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esg_goals', to='api.organization')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_esg_goals', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Objetivo ESG',
                'verbose_name_plural': 'Objetivos ESG',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ESGAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('expected_impact', models.TextField(blank=True, null=True, verbose_name='Enfoque/Impacto Esperado')),
                ('actual_result', models.TextField(blank=True, null=True, verbose_name='Resultado Real/Logro')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('in_progress', 'En Progreso'), ('paused', 'Pausado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='planned', max_length=20, verbose_name='Estado')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso %')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Presupuesto')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costo Real')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='esg.esgcategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_esg_actions', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='esg.esggoal', verbose_name='Objetivo Asociado')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esg_actions', to='api.organization')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_esg_actions', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('team_members', models.ManyToManyField(blank=True, related_name='esg_action_team', to=settings.AUTH_USER_MODEL, verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Acción ESG',
                'verbose_name_plural': 'Acciones ESG',
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
