# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre de la Organización")),
                ("rol", models.CharField(max_length=100, verbose_name="Rol del usuario")),
                ("empleados", models.CharField(max_length=50, verbose_name="Cantidad de empleados")),
                ("rut", models.CharField(max_length=20, verbose_name="RUT")),
                ("sector", models.CharField(choices=[("manufactura", "Manufactura"), ("tecnologia", "Tecnología/Software"), ("retail", "Retail/Comercio"), ("servicios", "Servicios profesionales"), ("alimentos", "Alimentos y bebidas"), ("construccion", "Construcción"), ("logistica", "Logística/Transporte"), ("energia", "Energía"), ("turismo", "Turismo/Hospitalidad")], max_length=50, verbose_name="Sector/Industria")),
                ("modo", models.CharField(choices=[("cumplimiento", "Cumplimiento"), ("accion", "Acción"), ("liderazgo", "Liderazgo")], max_length=50, verbose_name="Modo")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="organizations", to=settings.AUTH_USER_MODEL, verbose_name="Usuario")),
            ],
            options={
                "verbose_name": "Organización",
                "verbose_name_plural": "Organizaciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
