# Generated by Django 4.2.7 on 2026-01-04 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_add_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('push_notifications', models.BooleanField(default=False, verbose_name='Notificaciones push')),
                ('weekly_digest', models.BooleanField(default=True, verbose_name='Resumen semanal')),
                ('alerts_emissions', models.BooleanField(default=True, verbose_name='Alertas de emisiones')),
                ('alerts_compliance', models.BooleanField(default=True, verbose_name='Alertas de cumplimiento')),
                ('alerts_deadlines', models.BooleanField(default=True, verbose_name='Recordatorios de fechas')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='light', max_length=10, verbose_name='Tema')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português'), ('fr', 'Français')], default='es', max_length=5, verbose_name='Idioma')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=15, verbose_name='Formato de fecha')),
                ('timezone', models.CharField(choices=[('Europe/Madrid', 'Europe/Madrid (CET)'), ('Europe/London', 'Europe/London (GMT)'), ('America/New_York', 'America/New_York (EST)'), ('America/Los_Angeles', 'America/Los_Angeles (PST)'), ('America/Mexico_City', 'America/Mexico_City (CST)'), ('America/Bogota', 'America/Bogota (COT)'), ('America/Santiago', 'America/Santiago (CLT)'), ('America/Buenos_Aires', 'America/Buenos_Aires (ART)')], default='Europe/Madrid', max_length=50, verbose_name='Zona horaria')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA habilitado')),
                ('session_timeout', models.IntegerField(default=30, verbose_name='Tiempo de sesión (minutos)')),
                ('ip_whitelist_enabled', models.BooleanField(default=False, verbose_name='Lista blanca de IPs')),
                ('ip_whitelist', models.TextField(blank=True, null=True, verbose_name='IPs permitidas')),
                ('api_enabled', models.BooleanField(default=False, verbose_name='API habilitada')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Key')),
                ('webhooks_enabled', models.BooleanField(default=False, verbose_name='Webhooks habilitados')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL del webhook')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google Workspace'), ('microsoft', 'Microsoft 365'), ('slack', 'Slack'), ('zapier', 'Zapier'), ('salesforce', 'Salesforce')], max_length=50, verbose_name='Proveedor')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Conectado')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Token de acceso')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Token de refresco')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del token')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadatos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integración',
                'verbose_name_plural': 'Integraciones',
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
