# Generated by Django 4.2.7 on 2026-01-04 04:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Análisis')),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puntuación de Cumplimiento (%)')),
                ('requirements_total', models.IntegerField(default=0, verbose_name='Total Requisitos')),
                ('requirements_compliant', models.IntegerField(default=0, verbose_name='Requisitos Cumplidos')),
                ('requirements_partial', models.IntegerField(default=0, verbose_name='Requisitos Parciales')),
                ('requirements_non_compliant', models.IntegerField(default=0, verbose_name='Requisitos No Cumplidos')),
                ('executive_summary', models.TextField(blank=True, null=True, verbose_name='Resumen Ejecutivo')),
                ('key_findings', models.JSONField(blank=True, default=list, verbose_name='Hallazgos Clave')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='Recomendaciones')),
                ('ai_analysis_result', models.JSONField(blank=True, default=dict, verbose_name='Resultado Análisis IA')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Análisis de Cumplimiento',
                'verbose_name_plural': 'Análisis de Cumplimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('document_type', models.CharField(choices=[('policy', 'Política'), ('procedure', 'Procedimiento'), ('manual', 'Manual'), ('record', 'Registro'), ('certificate', 'Certificado'), ('audit_report', 'Informe de Auditoría'), ('evidence', 'Evidencia'), ('contract', 'Contrato'), ('training', 'Material de Capacitación'), ('other', 'Otro')], default='other', max_length=50, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='compliance/documents/%Y/%m/', verbose_name='Archivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Archivo')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Texto Extraído')),
                ('extraction_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Extracción')),
                ('analysis_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado de Análisis')),
                ('analysis_error', models.TextField(blank=True, null=True, verbose_name='Error de Análisis')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('is_current', models.BooleanField(default=True, verbose_name='Versión Actual')),
            ],
            options={
                'verbose_name': 'Documento de Cumplimiento',
                'verbose_name_plural': 'Documentos de Cumplimiento',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('category', models.CharField(choices=[('sustainability', 'Sostenibilidad'), ('environmental', 'Ambiental'), ('security', 'Seguridad de la Información'), ('governance', 'Gobernanza'), ('quality', 'Calidad'), ('social', 'Social/Laboral'), ('financial', 'Financiero'), ('data_privacy', 'Privacidad de Datos')], max_length=50, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versión')),
                ('issuing_body', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organismo Emisor')),
                ('official_url', models.URLField(blank=True, null=True, verbose_name='URL Oficial')),
                ('last_updated', models.DateField(blank=True, null=True, verbose_name='Última Actualización')),
                ('analysis_prompt', models.TextField(blank=True, help_text='Instrucciones específicas para la IA al analizar documentos para este framework', null=True, verbose_name='Prompt de Análisis IA')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Framework de Cumplimiento',
                'verbose_name_plural': 'Frameworks de Cumplimiento',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código del Requisito')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('policy', 'Políticas'), ('procedure', 'Procedimientos'), ('control', 'Controles'), ('documentation', 'Documentación'), ('training', 'Capacitación'), ('audit', 'Auditoría'), ('reporting', 'Reporte'), ('governance', 'Gobernanza'), ('technical', 'Técnico'), ('organizational', 'Organizacional')], default='control', max_length=50, verbose_name='Categoría')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('evaluation_criteria', models.TextField(blank=True, null=True, verbose_name='Criterios de Evaluación')),
                ('evidence_required', models.TextField(blank=True, null=True, verbose_name='Evidencia Requerida')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Lista de palabras clave para detección automática', verbose_name='Palabras Clave')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='compliance.complianceframework', verbose_name='Framework')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='compliance.compliancerequirement', verbose_name='Requisito Padre')),
            ],
            options={
                'verbose_name': 'Requisito de Cumplimiento',
                'verbose_name_plural': 'Requisitos de Cumplimiento',
                'ordering': ['framework', 'order', 'code'],
                'unique_together': {('framework', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('report_type', models.CharField(choices=[('gap_analysis', 'Análisis de Brechas'), ('compliance_status', 'Estado de Cumplimiento'), ('roadmap', 'Roadmap de Cumplimiento'), ('executive_summary', 'Resumen Ejecutivo'), ('audit_preparation', 'Preparación Auditoría'), ('progress_report', 'Reporte de Progreso')], max_length=50, verbose_name='Tipo de Reporte')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('docx', 'Word'), ('html', 'HTML'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='Formato')),
                ('file', models.FileField(blank=True, null=True, upload_to='compliance/reports/%Y/%m/', verbose_name='Archivo')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Contenido')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Inicio Período')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Fin Período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyses', models.ManyToManyField(related_name='reports', to='compliance.complianceanalysis', verbose_name='Análisis Incluidos')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('frameworks', models.ManyToManyField(related_name='reports', to='compliance.complianceframework', verbose_name='Frameworks')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='api.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Reporte de Cumplimiento',
                'verbose_name_plural': 'Reportes de Cumplimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('compliant', 'Cumple'), ('partial', 'Cumplimiento Parcial'), ('non_compliant', 'No Cumple'), ('not_applicable', 'No Aplica'), ('pending_review', 'Pendiente Revisión')], default='pending_review', max_length=20, verbose_name='Estado')),
                ('severity', models.CharField(choices=[('critical', 'Crítico'), ('high', 'Alto'), ('medium', 'Medio'), ('low', 'Bajo'), ('info', 'Informativo')], default='medium', max_length=20, verbose_name='Severidad')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confianza IA (%)')),
                ('finding', models.TextField(blank=True, null=True, verbose_name='Hallazgo')),
                ('evidence_found', models.TextField(blank=True, null=True, verbose_name='Evidencia Encontrada')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Recomendación')),
                ('remediation_plan', models.TextField(blank=True, null=True, verbose_name='Plan de Remediación')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='Fecha Resolución')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='compliance.complianceanalysis', verbose_name='Análisis')),
                ('relevant_documents', models.ManyToManyField(blank=True, related_name='related_gaps', to='compliance.compliancedocument', verbose_name='Documentos Relevantes')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='compliance.compliancerequirement', verbose_name='Requisito')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gaps', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Brecha de Cumplimiento',
                'verbose_name_plural': 'Brechas de Cumplimiento',
                'ordering': ['analysis', 'severity', 'requirement__order'],
            },
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='frameworks',
            field=models.ManyToManyField(blank=True, related_name='documents', to='compliance.complianceframework', verbose_name='Frameworks Relacionados'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='api.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='compliance.compliancedocument', verbose_name='Versión Anterior'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_compliance_docs', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='complianceanalysis',
            name='documents',
            field=models.ManyToManyField(related_name='analyses', to='compliance.compliancedocument', verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='complianceanalysis',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='compliance.complianceframework', verbose_name='Framework'),
        ),
        migrations.AddField(
            model_name='complianceanalysis',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_analyses', to='api.organization', verbose_name='Organización'),
        ),
    ]
